Bump setuptools minimum version to 77.0.0
for PEP 639 support.
Fix the following issue when installing on older setuptools:

```
ValueError: invalid pyproject.toml config: `project.license`.
configuration error: `project.license` must be valid exactly by one definition (2 matches found):

    - keys:
        'file': {type: string}
      required: ['file']
    - keys:
        'text': {type: string}
      required: ['text']
```